EMB-64 Update check_message.yml

diff --git a/.github/workflows/check_message.yml b/.github/workflows/check_message.yml
--- a/.github/workflows/check_message.yml
+++ b/.github/workflows/check_message.yml
@@ -1,4 +1,4 @@
-name: Commit Workflow
+name: Commit Message Validation
 
 on:
   push:
@@ -6,27 +6,15 @@ on:
       - main
 
 jobs:
-  commit:
+  validate-commit-message:
     runs-on: ubuntu-latest
-
+    
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v2
-
-    - name: Check commit message
-      id: check_commit
-      run: |
-        commit_message=$(git log --format=%B -n 1 ${{ github.sha }})
-        if [[ $commit_message != *"EMB-"* ]]; then
-          echo "::set-output name=commit_message::EMB-51"
-        else
-          echo "::set-output name=commit_message::$commit_message"
-        fi
-
-    - name: Create new commit
-      run: |
-        new_commit_message="${{ steps.check_commit.outputs.commit_message }}"
-        git config --local user.email "action@github.com"
-        git config --local user.name "GitHub Action"
-        git commit --amend -m "$new_commit_message"
-        git push --force
+      - name: Check Commit Message
+        id: commit-message-check
+        run: |
+          commit_message=$(git log -1 --pretty=%B)
+          if [[ ! $commit_message =~ EMB- ]]; then
+            echo "::error::You need to link your pushes with Jira issues"
+            exit 1
+          fi
